# -*- coding: utf-8 -*-
"""Number_Guessing_Game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18UooFg6q-JdJSWLNNpHqUlF0dAqw9_T3
"""

import random

print("Welcome to the Number Guess Game 🎮")
print("You're going to enter a number, and I'm going to guess if it's correct!")
print("Guess a number between 1 and 100")

number = random.randint(1, 100)

while True:
    guess = input("Enter your guess: ")

    if guess.strip() == "":
        print("Please enter a number!")
        continue

    if not guess.isdigit():
        print("Invalid input! Only numbers are allowed.")
        continue

    guess = int(guess)

    if guess < number:
        print("Too Low! 🤧")
    elif guess > number:
        print("Too High! 😮")
    else:
        print("🎉 Correct! Your guess is right! 👍")
        break